package com.picme.entity;

import java.io.Serializable;

public class Image implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.album_id
     *
     * @mbggenerated
     */
    private Integer albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.ord
     *
     * @mbggenerated
     */
    private Integer ord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table imgs
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.id
     *
     * @return the value of imgs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.id
     *
     * @param id the value for imgs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.path
     *
     * @return the value of imgs.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.path
     *
     * @param path the value for imgs.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.user_id
     *
     * @return the value of imgs.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.user_id
     *
     * @param userId the value for imgs.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.type
     *
     * @return the value of imgs.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.type
     *
     * @param type the value for imgs.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.album_id
     *
     * @return the value of imgs.album_id
     *
     * @mbggenerated
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.album_id
     *
     * @param albumId the value for imgs.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.ord
     *
     * @return the value of imgs.ord
     *
     * @mbggenerated
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.ord
     *
     * @param ord the value for imgs.ord
     *
     * @mbggenerated
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Image other = (Image) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getAlbumId() == null ? other.getAlbumId() == null : this.getAlbumId().equals(other.getAlbumId()))
            && (this.getOrd() == null ? other.getOrd() == null : this.getOrd().equals(other.getOrd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getAlbumId() == null) ? 0 : getAlbumId().hashCode());
        result = prime * result + ((getOrd() == null) ? 0 : getOrd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", path=").append(path);
        sb.append(", userId=").append(userId);
        sb.append(", type=").append(type);
        sb.append(", albumId=").append(albumId);
        sb.append(", ord=").append(ord);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}