package com.picme.mapper;

import com.picme.entity.PhotoAlbum;
import com.picme.entity.PhotoAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PhotoAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int countByExample(PhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int deleteByExample(PhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int insert(PhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int insertSelective(PhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    List<PhotoAlbum> selectByExampleWithRowbounds(PhotoAlbumExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    List<PhotoAlbum> selectByExample(PhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    PhotoAlbum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PhotoAlbum record, @Param("example") PhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PhotoAlbum record, @Param("example") PhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PhotoAlbum record);
}